name: tillage_farms
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  nhost_sdk: 2.1.1
  nhost_flutter_graphql: 1.1.5
  nhost_flutter_auth: 1.0.11
  nhost_graphql_adapter: 1.0.14
  flutter_dotenv: 5.0.2
  google_fonts: 2.3.1
  flutter_svg: 1.0.3
  iconsax: 0.0.8
  hive_flutter: 1.1.0
  auto_route: 3.2.4
  qlevar_router: 1.5.11
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/svg/
    - .env.development
    - .env.production
  uses-material-design: true

